### ISSUE TITLE
Guitar Pro parts export

### ISSUE THREAD

**Issue by PyroBillie** [fholger/RocksmithToTab#43]
Hi there, I've noticed some people are uploading the GP files to UG. Yet usually always the mods of UG make this comment: "4.8. Missing GP song parts. Please mark all parts of the song (Intro, Chorus, Verse, Solo, etc). In addition to Shift + Insert; In GP7 you can also use the Menu->Section->Edit; In GP6 you can use Menu-Section->Insert/Remove."
Would it be possible to change the export so that this happens?

**Comment by fholger** [comment]
Far as I remember, the tool already writes all available section markers from the original psarc to the output, so short of inventing some I wouldn't know what to do.

Either way, I'm afraid I cannot support uploading the produced files to UG or any other sites due to legal reasons. The tabs are property of Ubisoft and whoever holds the rights of the particular song. If you don't have explicit permission, I'd advise not sharing them :)

**Comment by PyroBillie** [comment]
It does indeed export the 'section' but as text, this is what bothers the UG mods.

We don't share the Rocksmith OG tabs ofcourse, but our own Custom charts :) which are based on .. custom tabs found on UG

**Comment by fholger** [comment]
Ah. I vaguely remember that the way to define actual sections in GP files was not compatible with the way they were provided from the Rocksmith arrangement, so implementing this might be quite challenging. I'm afraid that I do not currently have the time available to dig into that.
